version: "2"
services:
  data:
    image: pyar6329/rails-base:data-latest
    volumes:
      - ./var/postgresql/data:/var/lib/postgresql/data
  postgresql:
    restart: always
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=rails
      - POSTGRES_USER=rails
      - POSTGRES_DB=rails
    volumes_from:
      - data

  rails:
    restart: always
    build: ./builds
    volumes_from:
      - data
    depends_on:
      - postgresql
    links:
      - "postgresql:postgresql"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - DB_HOST=postgresql
	    - DB_PORT=5432
      - DB_DATABASE=rails
      - DB_USERNAME=rails
      - DB_PASSWORD=rails
      - SECRET_KEY_BASE=railshogehoge
    entrypoint: dockerize -wait tcp://postgresql:5432 -timeout 300s docker-entrypoint.sh
    command: unicorn_rails -c /usr/src/app/config/unicorn.rb -E production -p 3000 -o 0.0.0.0
